### ISSUE TITLE
pdflatex fails when one parameter is initial concentration

### ISSUE THREAD

**Issue by pmendes** [pdp10/sbpipe#221]
If one of the parameters in the parameter estimation is an initial concentration, the final compilation of pdflatex fails with this error:

! LaTeX Error: Unknown graphics extension: .FeSkinFur._0.png.

in this case the parameter was [FeSkinFur]_0 as named by COPASI (the initial concentration of that species). 

The problem seems to be with the \includegraphics directive that seems to look for the first . to check the extension, and in this case it sees ._0 rather than .png and aborts. Even though this is a latex problem, the easiest solution to this would be to make sure sbpipe never names any PNG file with more than one dot (so that there is a single .png).

**Comment by pmendes** [comment]
Seems like this is a well known issue... (see [this](https://tex.stackexchange.com/questions/10574/includegraphics-dots-in-filename)). The top answer there seems to be the easiest solution as you will only have to change the code for writing the .tex file.

**Comment by pdp10** [comment]
Thanks for reporting this. I will look into this asap.

**Comment by pdp10** [comment]
Confirmed.

**Comment by pdp10** [comment]
The commit f372583 fixes the problem for me. I also included your suggestion (post 2) as an additional backup solution. 
Currently, this patch is in `bugfix221`. Would it be possible for you to run your model using this branch, please?

**Comment by pmendes** [comment]
This has fixed the problem with my model too. Thanks

**Comment by pdp10** [comment]
:+1:  Thank you for letting me know.
